### ISSUE TITLE
Playlists stopped being returned

### ISSUE THREAD

**Issue by nukeop** [zaosoula/deezer-public-api#7]
**Describe the bug**
When using `deezer.editorial.charts` playlists are no longer returned.

**To Reproduce**
Call the above method.

**Expected behavior**
There used to be playlists there, along with artists, albums, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/12746779/219882438-03f9d798-3a0e-489a-ac05-18b545270657.png)

**Desktop (please complete the following information):**
All platforms

**Comment by zaosoula** [comment]
Will check !

**Comment by nukeop** [comment]
Sorry, forgot to mention that this went away recently as suddenly as it appeared. Probably something on Deezer's side. Thanks for this library!
